export const GET_ERRORS = "GET_ERRORS";
export const GET_MONSTER = "GET_MONSTER";
export const ADD_MONSTER_TO_STATE = "ADD_MONSTER_TO_STATE";
export const SAVE_MONSTER_TO_FAVORITES = "SAVE_MONSTER_TO_FAVORITES";
export const DELETE_MONSTER_TO_FAVORITES = "DELETE_MONSTER_TO_FAVORITES";
export const GET_FAVORITES = "GET_FAVORITES";

